repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.9.1 # Use the latest version of Black
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0 # Use the latest version of isort
    hooks:
      - id: isort
