name: restoration CI
on: [pull_request]
jobs:
  linting_and_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.10
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run linting checks
        run: ./bin/lint.sh
      - name: Run tests
        run: pytest --cov=restoration tests/
